/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pack;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;


@SpringBootApplication
@RestController
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class);
    }

    @GetMapping("/get")
    public List<Integer> hel() throws  SQLException {

        var con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/citiz_db", "pros", "secret");

        var st = con.createStatement();
        String sql = "select * from tab";
        var rs = st.executeQuery(sql);
        var list = new ArrayList<Integer>();
        while (rs.next())
        {
            int field = rs.getInt("id");
            list.add(field);
        }

        return list;
    }

}

