/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pack;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;


@SpringBootApplication
@RestController
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class);
    }


    @GetMapping("/sup")
    public String hello() throws IOException, InterruptedException {
        return "sup answered!";
    }
}

